#!/bin/sh

streamtonowhered start

if [ -z $UUT_CONNECT_HOST ] || [ -z $UUT_CONNECT_PORT ]; then
	echo PLEASE define UUT_CONNECT_HOST and UUT_CONNECT_PORT
	exit 1
fi
# remote command on HOST could be:
# nc -l -p 6666 -u | hexdump -e '28/4 "%08x," "\n"' | awk 'BEGIN { FS=","; latch1=0 }; { if ($27 != latch1){ print $0; latch1=$27 } }' | cut -d, -f1-8,24-

/usr/bin/logger -t uut_connect start $UUT_CONNECT_HOST $UUT_CONNECT_PORT sleep 2
sleep 2
shot=1
while [ 1 ]; do
	/usr/bin/logger -t uut_connect start $shot $UUT_CONNECT_HOST $UUT_CONNECT_PORT
	acq400_stream --spy 1 | nc $UUT_CONNECT_HOST $UUT_CONNECT_PORT
	sleep 1
	shot=$(($shot+1))
done
 

